matrix:
  include:
    - os: linux
      dist: trusty
      env: IRAFARCH=linux64 OS_VERS=trusty
    - os: linux
      dist: precise
      env: IRAFARCH=linux64 OS_VERS=precise
    - os: linux
      dist: trusty
      env: IRAFARCH=linux OS_VERS=trusty
      addons:
        apt:
          packages:
            - gcc-multilib
            - libcurl4-gnutls-dev:i386
            - libncurses5-dev:i386
            - libexpat1-dev:i386
    - os: linux
      dist: precise
      env: IRAFARCH=linux OS_VERS=precise
      addons:
        apt:
          packages:
            - gcc-multilib
            - libcurl4-gnutls-dev:i386
            - libncurses5-dev:i386
            - libexpat1-dev:i386
    - os: osx
      osx_image: xcode8.3
      env: IRAFARCH=macintel OS_VERS=sierra
    - os: osx
      osx_image: xcode7.3
      env: IRAFARCH=macintel OS_VERS=elcapitan
    - os: osx
      osx_image: xcode8.3
      env: IRAFARCH=macosx OS_VERS=sierra
    - os: osx
      osx_image: xcode7.3
      env: IRAFARCH=macosx OS_VERS=elcapitan

language: c

before_script:
  - build_tmp=`mktemp -d -t irafbuild.XXXXXXXXX`
  - ./install -v --term xterm --bindir $build_tmp/bin --cache $build_tmp/cache --imdir $build_tmp/imdir --root `pwd` < /dev/null || true
  - source unix/hlib/setup.sh
  - make ${IRAFARCH}
  - make sysgen

script:
  - ./test/run_tests
