os:
  - linux
  - osx

dist:
  - trusty

matrix:
  include:
    - os: linux
      dist: trusty
      env: IRAFARCH=linux64 LINUXDIST=trusty
      addons:
        apt:
          packages:
            - flex
            - byacc
    - os: linux
      dist: precise
      env: IRAFARCH=linux64 LINUXDIST=precise
      addons:
        apt:
          packages:
            - flex
            - byacc
    - os: linux
      dist: trusty
      env: IRAFARCH=linux LINUXDIST=trusty
      addons:
        apt:
          packages:
            - flex
            - byacc
            - gcc-multilib
            - libcurl4-gnutls-dev:i386
            - libncurses5-dev:i386
            - libexpat1-dev:i386
    - os: linux
      dist: precise
      env: IRAFARCH=linux LINUXDIST=precise
      addons:
        apt:
          packages:
            - flex
            - byacc
            - gcc-multilib
            - libcurl4-gnutls-dev:i386
            - libncurses5-dev:i386
            - libexpat1-dev:i386
    - os: osx
      env: IRAFARCH=macintel
    - os: osx
      env: IRAFARCH=macosx

language: c

before_script:
  - build_tmp=`mktemp -d`
  - ./install -v --term xterm --bindir $build_tmp/bin --cache $build_tmp/cache --imdir $build_tmp/imdir --root `pwd` < /dev/null || true
  - source unix/hlib/setup.sh
  - make ${IRAFARCH}
  - make sysgen

script:
  - source unix/hlib/setup.sh
  - ./test/run_tests
